### ISSUE TITLE
Dot Gov top level domain

### ISSUE THREAD

**Issue by bruce-usab** [GSA/openacr-editor#46]
Are there any plans to migrate to a dot gov domain like Federalist?

Somewhat relatedly, migrating from github.io to Federalist is (1) harder than it seems like it should be, and (2) not well documented.

Ping to @drewnielson and @kengdoj who had to figure out the minutia for the [ictbaseline](https://github.com/atbcb/ICTTestingBaseline).

**Comment by drewnielson** [comment]
We're discussing hosting the editor tool under a subdomain on section508.gov.
Plan not finalized yet.
